connectors:
  CDIR Results:
    action:
      name: download:file
    runner:
      name: DC1
    parameters:
      Use Path: "true"
      Path: "C:\\path\\to\\directory"

jobs:
  CDIR Incident Response:
    tags:
      - Demo
      - FromYaml
    runners:
      tags:
        - Customer2
        - IR
    schedule:
      type: RunNow
    actions:
      - name: secops:cdirwparams
        parameters:
          MemoryDump: "false"
          MFT: "false"
          Secure: "false"
          UsnJrnl: "false"
          EventLog: "true"
          Prefetch: "false"
          Registry: "true"
          WMI: "false"
          SRUM: "false"
          Web: "false"
          Target: "C:\\"
      - name: download:file
        parameters:
          Use Path: "true"
          File Path: "C:\\path\\config.ini"
        connector:
          name: CDIR Results
