name: Sync-Runway

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  syncJobs:
    runs-on: ubuntu-latest

    steps:
      # PS Module Cacher
      - name: Install and cache PowerShell modules
        uses: potatoqualitee/psmodulecache@v5.1
        with:
          modules-to-cache: BrazenCloud,BrazenCloud.YAML

      - uses: actions/checkout@v2

      - name: Test Sync Jobs on PR
        if: ${{ github.event_name == 'pull_request' }}
        shell: pwsh
        run: |
          $InformationPreference = 'Continue'
          Connect-BrazenCloud -Email ${{ secrets.RUNWAY_EMAIL }} -Password (ConvertTo-SecureString "${{ secrets.RUNWAY_PASSWORD }}" -AsPlainText -Force)
          foreach ($yaml in (Get-ChildItem "$($env:GITHUB_WORKSPACE)/yamls/*.yaml")) {
            Write-Host $yaml.Name
            Sync-BcResourceYaml -PathToYaml $yaml.FullName -Test
          }

      - name: Sync Jobs on push
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch'}}
        shell: pwsh
        run: |
          $InformationPreference = 'Continue'
          Connect-BrazenCloud -Email ${{ secrets.RUNWAY_EMAIL }} -Password (ConvertTo-SecureString "${{ secrets.RUNWAY_PASSWORD }}" -AsPlainText -Force)
          foreach ($yaml in (Get-ChildItem "$($env:GITHUB_WORKSPACE)/yamls/*.yaml")) {
            Write-Host $yaml.Name
            Sync-BcResourceYaml -PathToYaml $yaml.FullName
          }
